### ISSUE TITLE
Message text box size doesn't change

### ISSUE THREAD

**Issue by stefangreim** [felixb/smsdroid#22]
The sms message box doesn't change its size during text input. If there are more than two lines, I cannot see the last line if text. 
Nexus 5, Android 6.0

**Comment by felixb** [comment]
this build should fix it: http://ub0r.de/files/a9e1202d373ef495aa0934c6370bf6a5819aeff8-SMSdroid-release.apk

**Comment by rphair** [comment]
I am also having this issue, even after installing the test build for pull request #29 which fixes issue #21 for me.  Like in that other thread, I see the APK above has also been removed from the server.  Can I get an APK that includes both fixes, so I can fix this problem without unfixing the other one?  And what would we be waiting for before the app available to general public includes these fixes?

**Comment by felixb** [comment]
well, the changes made here were released to production in 2015. they are definitely included in the build provided in #29.

**Comment by rphair** [comment]
Here's what I see after having installed that build (on Nexus 5 with CM13).  No matter how many lines are added to the input window, and whether the lines are wrapped or carriage returned, the window never gets any bigger than this.
![screenshot_20160419-101230](https://cloud.githubusercontent.com/assets/2572798/14633872/7cc7c47e-0617-11e6-88fa-bd7bac3d2ff0.png)

**Comment by stefangreim** [comment]
Ok, just for information: I still have this behavior. I am not able to see more than the last two lines. But that is fine fore me.
The previous problem was, that I was not able to see the last line (in your case the Line3) if there were more than two lines in total.

**Comment by rphair** [comment]
@stefangreim - thanks for clarification.  Being limited to only seeing 2 lines of compose text is a serious limitation for me & probably others who send diplomatic / unabbreviated text messages. From UX perspective, note the screenshot above gives higher priority to messages distant in the conversation that it does to the message currently being composed. It should be possible to autogrow the field like in the old Mobile Boilerplate > Textarea autogrow plugin ([MBP.autogrow](https://github.com/h5bp/mobile-boilerplate/blob/master/js/helper.js)).
